title: AltDrag
url: https://stefansundin.github.io
baseurl: /altdrag
description: AltDrag brings the window moving behavior from Linux to Windows.
author: Stefan Sundin

# posts
permalink: /news/:year-:month-:day-:title.html

# build
plugins:
- jekyll-github-metadata
markdown: kramdown
kramdown:
  input: GFM
future: true
